### ISSUE TITLE
Instruction lacks some info

### ISSUE THREAD

**Issue by shurrman** [SegiH/Asbru-CM-Runner#3] opened 2021-11-13 13:43 UTC
Instruction says "Run sudo apt-get update && sudo install -y asbru-cm"
Need to add :
curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | sudo -E bash
sudo apt install asbru-cm

Also, even with XMing running, and export DISPLAY=:0, asbru-cm does not start - unable to connect... some permissions or what?

**Comment by SegiH** [comment] 2021-11-14 09:04
I just tested this out on a Windows 10 computer that I just installed WSL on. These are the steps that I followed

1. I installed WSL in a Powershell prompt with admin privileges with the command wsl --install -d Ubuntu to install WSL with Ubuntu as the distro and followed the prompts
2. I then did the curl command (see comment below) then sudo apt-get update && sudo apt install -f asbru-cm
3. export DISPLAY=:0
4. Install XMing, launched it and allowed it access through the Windows firewall.
5. Launch asbru-cm command and Asbru launches as you'd expect.

If you are getting an error, please reply with a screenshot of the error message so I can see what it says.

Re:
Need to add :
curl -1sLf 'https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh' | sudo -E bash

Thanks. I've added this to README

**Comment by shurrman** [comment] 2021-11-14 09:29
p. 4 seems crucial... I am not a Windows user, have no idea how to do it ))

**Comment by SegiH** [comment] 2021-11-14 09:33
Xming is a Windows program that you download and install like any Windows program

**Comment by shurrman** [comment] 2021-11-14 09:37
wow...
https://stackoverflow.com/questions/61110603/how-to-set-up-working-x11-forwarding-on-wsl2

**Comment by SegiH** [comment] 2021-11-14 18:51
Ok well the README specifically says that this has only been tested with WSL2.

If you aren't using WSL2 your mileage may vary

**Comment by SegiH** [comment] 2021-11-15 00:32
What os do you use?

**Comment by shurrman** [comment] 2021-12-08 20:24
Hi! Sorry for delay, I was on vacation (and mostly use Linux, haha!)
So: 
1. Had to add to .bashrc: `export DISPLAY=$(awk '/nameserver / {print $2; exit}' /etc/resolv.conf 2>/dev/null):0
export LIBGL_ALWAYS_INDIRECT=1`. Which leads to DISPLAY being 172.28.192.1:0 as WSL2 create a separate interface.
2. Need to change firewall setting, whatever firewall is there. A rule allowing TCP 6000 needs to be added. I added a rule allowing 6000 from my local nets. 
3. still a typo in p.3 (` sudo install -y asbru-cm` - `apt-get` missing)

Mostly [this post](https://stackoverflow.com/questions/61110603/how-to-set-up-working-x11-forwarding-on-wsl2) helped.

**Comment by SegiH** [comment] 2021-12-08 21:15
1. I just tested this out. I am on Windows 10 and use WSL2 with Ubuntu as my distro of choice and followed step 3 of my README instructions to manually launch asbru-cm and it worked as expected. I don't know why you would have to set DISPLAY to bind to the IP address of the nameserver from resolve.conf in order for this to work.
2.  Unless you specifically installed a firewall like ufw, you should not have a firewall installed in WSL, at least with the distro that I use. This might be helpful to know for those that choose to install a firewall in WSL but that is not the normal expected behavior.
3. I fixed the README to include the missing apt command. apt-get is not really used anymore since its best to use apt instead now.

**Comment by shurrman** [comment] 2021-12-08 22:03
he, I am not inventing problems, right )
1. installing WSL2 got me a new adapter, and in WSL it is ```aaa@shurrman:~$ ip addr show eth0
6: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:15:5d:c1:e9:de brd ff:ff:ff:ff:ff:ff
    inet 172.28.201.141/20 brd 172.28.207.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::215:5dff:fec1:e9de/64 scope link
       valid_lft forever preferred_lft forever```

**Comment by shurrman** [comment] 2021-12-08 22:05
2. It is about Windows firewall. And is obviously related to the above. When Windows firewall disabled - it works immediately. When enabling - does not. Adding a rule allowing X-server access from needed networks - resolves.
3. right, should be apt

**Comment by shurrman** [comment] 2021-12-08 22:08
I have Windows 10 Home 19043.1348 originally installed....
Will update it to 11 soon )

**Comment by shurrman** [comment] 2021-12-08 22:09
Just to clarify: WSL should be able to access X in the network sense. Seems like you do not have separate adapter/network for WSL. I do.

**Comment by shurrman** [comment] 2021-12-08 22:10
Probably should be closed as an issue. There is enough information here for someone who ever faces the same issues.

**Comment by SegiH** [comment] 2021-12-08 22:17
I  understand what you are saying. I also have multiple IP addresses show up if I run the command ip addr in an Ubuntu bash 
prompt. I just don't understand though why that matters because you bind display to a display number. The method that you are using by binding to the network interface is not the usual way that most people would access the display. 

As far as the Windows firewall issue goes, I have it enabled too and just checked and I don't have a rule for port 6000. I'm not sure why you had to add a rule like that,

I will close this issue because I agree with you that anyone else who has a WSL2 setup similar to yours can use your comments to figure out how get it to work

**Closed as completed by SegiH** 2021-12-08 22:17 UTC

**Comment by shurrman** [comment] 2021-12-08 22:21
Sure! But note the link to StackOverflow post I sent above. I am not alone ))

**Comment by shurrman** [comment] 2021-12-08 22:21
And thanks for the Runner!

**Comment by SegiH** [comment] 2021-12-08 22:29
Yes I just pulled it up and I see what you mean. X11 forwarding is not the norm but I guess there are quite a few people who do that.

These are the 2 lines that fixed the display forwarding for you right ?

```
export DISPLAY=$(awk '/nameserver / {print $2; exit}' /etc/resolv.conf 2>/dev/null):0
export LIBGL_ALWAYS_INDIRECT=1
```

If so, I will add them to the README. It seems important enough that it should be in there

You're welcome and thanks for the feedback.

When you upgrade to Windows 11, you won't need XMing. wsl2 on Windows 11 includes a window manager. You just launch asbru-cm and it will open. I am not sure if X11 forwarding  is affected by this or not.

In fact, I'd be interested to know because I may want to modify my app to not attempt to launch XMing if you are running the app on Windows 11 if my app is even needed on W11. I have to check on this because if W11 adds a shortcut in the start menu for GUI apps that you install in WSL2 then my app wouldn't be needed at all on W11.
